### ISSUE TITLE
Can't find variable: C72RfidScanner

### ISSUE THREAD

**Issue by sanjeevgehlot** [paulobunga/c72-rfid-scanner#10]
I followed both the below commands:

$ npm install c72-rfid-scanner --save

$ react-native link c72-rfid-scanner

When I run the app after build, it gives an error "Can't find variable: C72RfidScanner".

**Comment by paulobunga** [comment]
Hello, unfortunately, due to financial issues I decided to privatize any bug fixes and offer customer support going forward. If this is something that you might need help me in. Get in touch paulobunga.one@gmail.com
