### ISSUE TITLE
Issue while reading Tag

### ISSUE THREAD

**Issue by ie76** [paulobunga/c72-rfid-scanner#13]
i have this issue while reading a Tag. I don't know if the repo is still maintained, but here's the error i'm getting: 

`[Error: Attempt to invoke virtual method 'java.lang.String com.rscja.deviceapi.entity.UHFTAGInfo.getEPC()' on a null object reference]`

**Comment by paulobunga** [comment]
Hello, unfortunately, due to financial issues I decided to privatize any bug fixes and offer customer support going forward. If this is something that you might need help me in. Get in touch paulobunga.one@gmail.com.
