### ISSUE TITLE
..

### ISSUE THREAD

**Issue by Adnanakhter321** [paulobunga/c72-rfid-scanner#51]
Fine

**Comment by Adnanakhter321** [comment]
@paulobunga

**Comment by paulobunga** [comment]
Planning to update it later this week

**Comment by Adnanakhter321** [comment]
I need it urgent if you can do it this week, i will be very thankful to you.

**Comment by Adnanakhter321** [comment]
@paulobunga any update on this ?

**Comment by Adnanakhter321** [comment]
@paulobunga  any update on this ?
